{% set name = "stream-unzip" %}
{% set version = "0.0.84" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stream-unzip-{{ version }}.tar.gz
  sha256: 974586ac8f23b1e491f353fcfb1172c9471d04bd05c05f6b6146c26c126d7442

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - pycryptodome >=3.10.1
    - python >=3.5
    - stream-inflate >=0.0.12

test:
  imports:
    - stream_unzip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uktrade/stream-unzip
  summary: Python function to stream unzip all the files in a ZIP archive, without loading the entire ZIP file into memory or any of its uncompressed files
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
