{% set name = "stream-unzip" %}
{% set version = "0.0.93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7a042b488b084f81b5226eea8cc0a5dabcb4b9867e3d67db7d08adfbbbf33759

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6.7
    - hatchling
  run:
    - pycryptodome >=3.10.1
    - python >=3.6.7
    - stream-inflate >=0.0.12

test:
  imports:
    - stream_unzip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uktrade/stream-unzip
  summary: Python function to stream unzip all the files in a ZIP archive, without loading the entire ZIP file into memory or any of its uncompressed files
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
