{% set name = "stream-unzip" %}
{% set version = "0.0.97" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a25bdc547fc591ebb606a84f3c820048cf1275c5bb4c7d7f25572cd5cc109408

build:
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - maturin >=1.7.4,<2.0.0
  run:
    - python
    - pycryptodome >=3.10.1
    - stream-inflate >=0.0.12

test:
  imports:
    - stream_unzip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uktrade/stream-unzip
  summary: Python function to stream unzip all the files in a ZIP archive, without loading the entire ZIP file into memory or any of its uncompressed files
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
